item {
    name: "fish1"
    id: 1
    display_name: "fish1"
}
item {
    name: "fish2"
    id: 2
    display_name: "fish2"
}
item {
    name: "fish3"
    id: 3
    display_name: "fish3"
}
item {
    name: "fish4"
    id: 4
    display_name: "fish4"
}
item {
    name: "fish5"
    id: 5
    display_name: "fish5"
}
item {
    name: "fish6"
    id: 6
    display_name: "fish6"
}
item {
    name: "fish7"
    id: 7
    display_name: "fish7"
}
item {
    name: "fish8"
    id: 8
    display_name: "fish8"
}
item {
    name: "eel"
    id: 9
    display_name: "eel"
}